In [1]:
#Questions
#=========
#1.How has employment in Nigeria/Denmark varied over time
#2.What are the higest and lowest employment levels(which countries have them,where is nigeria on the spectrum)
#3.

In [2]:
import pandas as pd

daily_engagement = pd.read_csv('daily_engagement_full.csv')
len(daily_engagement['acct'].unique())

1237

In [5]:
import numpy as np
# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

print (countries)

['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Armenia'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina']


In [6]:
# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])
print(employment)

[ 55.70000076  51.40000153  50.5         75.69999695  58.40000153
  40.09999847  61.5         57.09999847  60.90000153  66.59999847
  60.40000153  68.09999847  66.90000153  53.40000153  48.59999847
  56.79999924  71.59999847  58.40000153  70.40000153  41.20000076]


In [17]:
# Change False to True for each block of code to see what it does

# Accessing elements
if True:
    print (countries[0])
    print (countries[3])

# Slicing
if True:
    print (countries[0:3])
    print (countries[:3])
    print (countries[17:])
    print (countries[:])

# Element types
if True:
    print (countries.dtype)
    print (employment.dtype)
    print (np.array([0, 1, 2, 3]).dtype)
    print (np.array([1.0, 1.5, 2.0, 2.5]).dtype)
    print (np.array([True, False, True]).dtype)
    print (np.array(['AL', 'AK', 'AZ', 'AR', 'CA']).dtype)

# Looping
if True:
    for country in countries:
        print ('Examining country {}'.format(country))

    for i in range(len(countries)):
        
        country_employment={}
        country = countries[i]
        country_employment = employment[i]
        #country_employment.concatenate(country[employment[i]])
        
        print ('Country {} has employment {}'.format(country,
                country_employment))


print(country_employment)


# Numpy functions
if True:
    print (employment.mean())
    print (employment.std())
    print (employment.max())
    print (employment.sum())



Afghanistan
Angola
['Afghanistan' 'Albania' 'Algeria']
['Afghanistan' 'Albania' 'Algeria']
['Bhutan' 'Bolivia' 'Bosnia and Herzegovina']
['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Armenia'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina']
<U22
float64
int64
float64
bool
<U2
Examining country Afghanistan
Examining country Albania
Examining country Algeria
Examining country Angola
Examining country Argentina
Examining country Armenia
Examining country Australia
Examining country Austria
Examining country Azerbaijan
Examining country Bahamas
Examining country Bahrain
Examining country Bangladesh
Examining country Barbados
Examining country Belarus
Examining country Belgium
Examining country Belize
Examining country Benin
Examining country Bhutan
Examining country Bolivia
Examining country Bosnia and Herzegovina
Country Afghanistan has employment 55.70000076
Count

In [22]:
def max_employment_1(countries, employment):
    '''
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    '''
    country_employment = dict(zip(employment, countries))
    max_country = country_employment[employment.max()]   # Replace this with your code
    
    max_value = employment.max()   # Replace this with your code

    return (max_country, max_value)

max_employment(countries, employment)

('Angola', 75.699996949999999)

In [24]:
def max_employment_2(countries, employment):
    '''
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    '''
    max_country = None
    max_employment = 0
    
    for i in range(len(countries)):
        country = countries[i]
        country_employment = employment[i]
        
        if country_employment > max_employment:
            max_country = country
            max_employment = country_employment                   
    
    return (max_country, max_employment)

max_employment_2(countries, employment)

('Angola', 75.699996949999999)

In [25]:
# the numpy way
def max_employment_3(countries, employment):
    '''
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    '''
    i = employment.argmax()
    return (countries[i],employment[i])
   

max_employment_3(countries, employment)

('Angola', 75.699996949999999)

In [27]:
import numpy as np

# Change False to True for each block of code to see what it does

# Arithmetic operations between 2 NumPy arrays
if True:
    a = np.array([1, 2, 3, 4])
    b = np.array([1, 2, 1, 2])
    
    print (a + b)
    print (a - b)
    print (a * b)
    print (a / b)
    print (a ** b)

[2 4 4 6]
[0 0 2 2]
[1 4 3 8]
[ 1.  1.  3.  2.]
[ 1  4  3 16]


In [7]:
import numpy as np
# Arithmetic operations between a NumPy array and a single number
if True:
    a = np.array([1, 2, 3, 4])
    b = 2
    
    print (a + b)
    print (a - b)
    print (a * b)
    print (a / b)
    print (a ** b)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[ 0.5  1.   1.5  2. ]
[ 1  4  9 16]


In [8]:
# Logical operations with NumPy arrays
if True:
    a = np.array([True, True, False, False])
    b = np.array([True, False, True, False])
    
    print (a & b)
    print (a | b)
    print (~a)
    
    print (a & True)
    print (a & False)
    
    print (a | True)
    print (a | False)

[ True False False False]
[ True  True  True False]
[False False  True  True]
[ True  True False False]
[False False False False]
[ True  True  True  True]
[ True  True False False]


In [11]:
# Comparison operations between 2 NumPy Arrays
if True:
    a = np.array([1, 2, 3, 4, 5])
    b = np.array([5, 4, 3, 2, 1])
    
    print (a > b)
    print (a >= b)
    print (a < b)
    print (a <= b)
    print (a == b)
    print (a != b)

[False False False  True  True]
[False False  True  True  True]
[ True  True False False False]
[ True  True  True False False]
[False False  True False False]
[ True  True False  True  True]


In [18]:
# First 20 countries with school completion data
countries = np.array([
       'Algeria', 'Argentina', 'Armenia', 'Aruba', 'Austria','Azerbaijan',
       'Bahamas', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Bolivia',
       'Botswana', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cambodia', 'Cameroon', 'Cape Verde'
])

# Female school completion rate in 2007 for those 20 countries
female_completion = np.array([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

# Male school completion rate in 2007 for those 20 countries
male_completion = np.array([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])

def overall_completion_rate(female_completion, male_completion):
    '''
    Fill in this function to return a NumPy array containing the overall
    school completion rate for each country. The arguments are NumPy
    arrays giving the female and male completion of each country in
    the same order.
    '''
    overall_completion= (female_completion + male_completion)/2
    #overall_completion= np.concatenate((female_completion,male_completion),axis=0)
    
    return overall_completion


overall_completion_rate(female_completion,male_completion)

array([ 192.83205,  205.28855,  202.82258,  186.63257,  206.91115,
        196.29643,  204.70226,  183.5571 ,  185.67095,  179.31151,
        198.43743,  196.96855,  188.34567,  234.67025,  196.55129,
         66.08078,   83.81045,  181.92593,  114.16808,  186.1203 ])